### PR TITLE
GTK 3.20 :: Fixed notebook asymmetrical padding

### PR DESCRIPTION
**Pull request by megax**

### CODE REVIEW

**Comment by megax** [comment]
@khurshid-alam Fixed. Looks better :)

**Comment by megax** [comment]
> Should be at-least 5/10....... $spacing ($spacing * 2);

okay, fix it

**Comment by megax** [comment]
> Should be at-least 5/10....... $spacing ($spacing \* 2);

@khurshid-alam okay, fix

**Comment by lots0logs** [comment]
Please see my comment here: https://github.com/numixproject/numix-gtk-theme/pull/613#issuecomment-255810916

**Pull request merged**
