### PR TITLE
GTK 3.20 :: Clean code

### PR DESCRIPTION
**Pull request by megax**

### CODE REVIEW

**Comment by megax** [comment]
@khurshid-alam just clean.

**Comment by satya164** [comment]
Can you address bot's concerns please? If we want this behavior, we should change the lint config.

**Comment by megax** [comment]
`rgba` support should be, but I can not solve.

**Comment by khurshid-alam** [comment]
If we disable `ColorVariable` in lint-config will it still inform of wrong values of predefined color? Like between `$white` & `white`. If not then I think it's better to keep it like that.

**Comment by khurshid-alam** [comment]
I personally use this: https://github.com/brigade/scss-lint

**Comment by lots0logs** [comment]
> If we disable ColorVariable in lint-config will it still inform of wrong values of predefined color? Like between $white & white. If not then I think it's better to keep it like that.

Yes, that's a separate linter than the ColorVariable one. I think in the case of the colors flagged in this PR, the proper code would be to use either [gtk](https://developer.gnome.org/gtk3/stable/chap-css-overview.html#id-1.5.2.3.8.14) or [sass'](http://sass-lang.com/documentation/Sass/Script/Functions.html#transparentize-instance_method) built-in helper functions for mixing colors with alpha. For example:
- **SASS:** `transparentize($dark_shadow, .06);`
- **GTK:** `alpha(.06, $dark_shadow);`

**Comment by megax** [comment]
Fixed code.

**Pull request merged**
