### PR TITLE
GTK 3.20 :: Selection mode rewrite. Fixed #545

### LINKED ISSUE #545: GTK 3.20 :: headerbar and .titlebar :: Selection mode
Not work (headerbar):
image

### PR DESCRIPTION
**Pull request by megax**
image

### CODE REVIEW

**Comment by megax** [comment]
@khurshid-alam You should be modified?

**Comment by khurshid-alam** [comment]
Please rebase.

**Comment by megax** [comment]
@khurshid-alam Rebased.

**Comment by khurshid-alam** [comment]
#541 should be merged first, then this

**Pull request merged**
