### PR TITLE
GTK 3.22 and GTK 3.20 :: Fixes #571 warning. Other fix.

### LINKED ISSUE #571: GTK 3.22 Issues
According to [this page](https://developer.gnome.org/gtk3/stable/GtkCssProvider.html#GtkCssProvider.description) in GTK docs, we should not need to symlink `gtk-3.22` to `gtk-3.20` directory. It should "just work" as it is now. Just need to confirm that is actually the case.

### PR DESCRIPTION
**Pull request by megax**
Other fix:
https://bugzilla.gnome.org/show_bug.cgi?id=767058

### CODE REVIEW

**Comment by megax** [comment]
@lots0logs, @khurshid-alam Fixed GTK 3.22 warning.

**Comment by lots0logs** [comment]
@megax There shouldnt be any need for a symlink. See [here](https://github.com/numixproject/numix-gtk-theme/issues/571#issue-178526796) for details.

**Comment by megax** [comment]
@khurshid-alam Sorry, I can no support Bluetooth and no app =/

```
font-style: normal;
font-size: 50px;
```

It works? Because then i correct.

**Comment by megax** [comment]
@lots0logs Okay, sorry, old modification =/ Work without it, fix it :)

Edit: Fixed

**Pull request merged**
