### PR TITLE
gtk3.20: Notebook rewirte old numix style.

### PR DESCRIPTION
**Pull request by megax**
New style:

Default:
image
image

Backdrop:
image

Hover:
image

Other:
image

Minimal bug: bottom border (select color) 1 px bug (left, right)
Base code: Adwaita

### CODE REVIEW

**Comment by megax** [comment]
@lots0logs @khurshid-alam Style? :)

**Comment by lots0logs** [comment]
@megax Ah, sorry I should have mentioned I was working on the notebook tabs. I just pushed my completed work on redesigning them :grimacing:

**Comment by megax** [comment]
@lots0logs No problem :) Close pull request? :)

**Comment by khurshid-alam** [comment]
@megax With **gtk-3.22** bottom border on hover on notebook tab is missing (for numix stable release-2.6)? 

missing-tab

Also I am redesigning button color. So notebook tabs needs refactoring.

**Comment by megax** [comment]
@lots0logs Rewrite full notebook code. I don't know WHY canceled =/

**Comment by khurshid-alam** [comment]
@megax Oh I commented on wrong section....but anyway this is yours (db5526375b849fe882c31245629e56efbaec9876) ......it needs to be updated for 3.22...

Present code is better....we only need to add few bits from old design.

**Comment by megax** [comment]
What needs to change? https://db.tt/9lJQoTrBkm Looks good. Did minimal color correction :)

**Comment by khurshid-alam** [comment]
@megax 

1. grey bottom border on hover (like in the image). It should be straight....and not trapezoidal.
2. Notebook tab color (normal, hover, checked/active, active:hover) should be as close to old color (Gtk-3.18) if possible.

**Comment by khurshid-alam** [comment]
@megax 
Our notebook code is bugged here: https://github.com/numixproject/numix-gtk-theme/blob/master/src/gtk-3.20/scss/widgets/_notebook.scss#L155

`header.top > tab > box`........we should **never** try to do anything with `box`. It is a generic container. We should only theme css/nodes. Lostlogs did this to fix a bug in audacious...but it should be fixed for audacious.


But your old is more similar to ours. In my testing it is working.
Can you update your notebook design (2f96e44265c372a748bc6e7d1f2416af186acab3)  to present status ? May be open a separate PR?

**Comment by lots0logs** [comment]
@khurshid-alam 
>Our notebook code is bugged here: https://github.com/numixproject/numix-gtk-theme/blob/master/src/gtk-3.20/scss/widgets/_notebook.scss#L155
>
>header.top > tab > box........we should never try to anything with box. It is a generic container. We should only theme css/nodes.

How is it bugged? The selector is actually very specific. The only way it could possibly not work as intended  is with some custom widgets that have been modified in some way from standard gtk notebook widget.

**Comment by khurshid-alam** [comment]
@lots0logs 

>The only way it could possibly not work as intended with custom widgets that have been modified in some way from standard gtk notebook widget.

Terminix exactly does that. Setting custom border (or shadow?) for tab > box. For me notebook tabs are jumping off when I hover over them (when using vertically window inside horizontal window).

And I don't like how we are drawing border
 first on the box
 `header.top > tab> box { border-width: 2px;}` and then again on the tab
 `header.top > tab { border-bottom-width: 1px;}`

notebook-tab-border

I don't think this is right. Because of this if  I want to introduce bottom border on :hover (like I showed in above comment ), it simply can not be done. The moment border appears on hover, label and close button automatically jumps up and I can't fix it with margin.

**Comment by lots0logs** [comment]
@khurshid-alam Still that does not equate to it being bugged. You cant fault it for not working on some random custom widget that it was not written to support in the first place. I'll take a look at terminix and fix it asap.

**Pull request closed without merging**
