### PR TITLE
[gtk3.20] Redesign windows csd decoration

### LINKED ISSUE #333: Certain GTK applications have no border or shadow
I'm not sure what term I should use to describe them, but certain GTK applications which use the bigger title bar style don't have borders or shadows. This also makes it difficult to resize these windows.
noborder

### PR DESCRIPTION
**Pull request by megax**
Fixed and redesign:
- Window shadow bug fix (https://github.com/numixproject/numix-gtk-theme/commit/3cc526c0d6b1a59049b3d91ba490fb66b5281f1c)
- Added csd window border.

Old:
image

New:
image

Fix https://github.com/numixproject/numix-gtk-theme/issues/333

### CODE REVIEW

**Comment by megax** [comment]
@lots0logs @khurshid-alam @marmis85 Redesign csd window decoration. (fix https://github.com/numixproject/numix-gtk-theme/commit/3cc526c0d6b1a59049b3d91ba490fb66b5281f1c)

**Comment by khurshid-alam** [comment]
@megax We can not use `box-shadow` under `.solid.csd`....it will break Unity(and any other compiz session) in yakkety. See issue #206. However for the time being it can be merged.

**Comment by megax** [comment]
@khurshid-alam Ohh... =/ Fixed `.solid-csd` unity/compiz regression.

**Comment by khurshid-alam** [comment]
@megax Include `.ssd` border tweak (`box-shadow: 0 0 0 1px $wm_border_focused`) for Gtk-3.18 as well. It fixes #270

**Comment by megax** [comment]
@khurshid-alam Fixed :)

**Comment by khurshid-alam** [comment]
@megax You misunderstood. I want you to include/add that particular line of code in https://github.com/numixproject/numix-gtk-theme/blob/master/gtk-3.0/scss/widgets/_window.scss#L53 as it is also required by Gtk-3.18. And also include `"Fixes #270"` in the commit message.

**Comment by megax** [comment]
Ohh.. Sorry =/ This corresponds to? :)

**Comment by satya164** [comment]
I would prefer to have a border only when there is no shadow. Otherwise the border doesn't do anything and looks ugly.

**Comment by megax** [comment]
@khurshid-alam Oh.. Sorry, fix.
@satya164 So it would be better?

Example:
image

**Comment by khurshid-alam** [comment]
Looks good. merging.

**Pull request merged**
