### PR TITLE
Xfce4 usability

### PR DESCRIPTION
**Pull request by achadwick**
Hi - I've been tweaking Numix's xfwm4 theme for greater usability (by my standards, anyway). Would you be interested in accepting:
- For those of us with single bottom panels or docks: when a window is maximized, allow the top-left and top-right pixels of the screen to hit window buttons that might be there.
- Bigger grips all round, because Xfwm4 doesn't have modern magic window borders that can be dragged even if the mouse isn't pointing at them, and 2 pixels is way too small for mice or (especially) tablets.
- Nice wide L-shaped bottom corner resize grips, rather than a measly 2x2 pixel blob.
- Optionally (separate commit), bigger grips only on the bottom ☺
- Bigger titlebar buttons, to make clicking them easier (and possible on the top row of screen pixels when the window is maximized). Note the glyph size and the spaces between them remains unchanged.
- Icons can be rebuilt from SVG, to ease maintenance. Slight stylistic change as a result, but still pretty much a pixel-perfect match to upstream ☺
- Add stick button. Xfwm now has its full complement of button types.

### CODE REVIEW

**Comment by satya164** [comment]
I had to revert the commit since Numix looked ugly and we needed more changes like GTK color pickup support etc. Feel free to maintain it in your own branch.

**Comment by achadwick** [comment]
I think the thicker borders were a vast improvement and the thin _1px_ ones are ugly. More objectively, they're almost impossible to use with a mouse now.

I believe GTK colour pickup was already merged.

**Comment by satya164** [comment]
@achadwick In my opinion, thinner border is nicer and maintains consistency with the metacity/mutter/unity themes.

About usability issues, yes, it's huge usability loss. But this is a problem with Greybird too, and not just Numix. I think @ochosi can talk to the xfwm4 dev to add an option to customize the grip area. It should be fixed in the window manager IMO.

About GTK color pickup being already merged, though @ochosi did the hard work, design of some buttons were changed with your pull request, and the result was something different than what I expected. Hence I reworked almost all the pixmaps. You can check the commits.

**Comment by toupeira** [comment]
FYI you can use Alt + right mouse button to resize a window anywhere in Xfwm.

**Comment by achadwick** [comment]
@toupeira I'm aware of that, but thanks all the same.  Using the key is no good for users of devices without keyboards, or for new users who don't know about the trick. And it does seem to be a move born of frustration (to me) rather than one of choice. 

IMO this should not be fixed in the window manager because there is no problem to be addressed really.  Xfwm already supports window resize handles, and it seems the responsibility of theme authors to provide users with reasonably sized resize edges.  The xfwm devs may have changed their mind about this, but that does appear to be the authors' expectation as expressed by the existing software. The question is, how should Numix and the  *birds meet this and their users' needs?

I've no usability preference between NeXT-style bottom bars or Chromium-style resize edges really. Win7's resize edges are too big and Fisher-Price though, even for me; I'm not keen on OSX-style resize corners, which don't play nice with terminal windows and seem to restrict or funnel my choices more than I like. Aesthetically, I prefer NeXT-style things with neat titlebar-height buttons, and for affordances to be made clearly visible.

**Comment by satya164** [comment]
@achadwick Why this shouldn't be fixed in XFWM? Metacity, Mutter all provide this functionality without restricting the theme designers choice for borders.

The latest Unity decorations don't have any border at all. Though we don't have any plans to go border-less anytime soon, how can we do this if the window manager doesn't have support for it? I see the only way to improve usability without forcing the theme designers to change their design is to have this functionality in the window manager itself.

**Comment by achadwick** [comment]
@satya164: see upstream <https://bugzilla.xfce.org/show_bug.cgi?id=11808>

My position has hardened, and neither Numix nor Xfwm4 are right. Upstream needs to do better. However it is the responsibility of theme authors to respect the foibles of different window managers and respond to them sensitively to them as designers.

If Numix does not do this for Xfce, which has no plans to change its way of working at present, then Numix is broken for Xfce.

**Comment by satya164** [comment]
I'm not the one responsible for making decisions here anymore, but it's disheartening to see Xfwm4 marking it as wont fix. They say themes are favouring looks, but aren't that what themes are for anyway?

**Comment by khurshid-alam** [comment]
@achadwick 

I don't want Numix to be broken on xfce. I might take e836f9a but I don't think I need other two.

**Pull request merged**
