### PR TITLE
Xfwm4: improve accessibility (wider bottom edge)

### PR DESCRIPTION
**Pull request by achadwick**
After #96 got applied then rolled back as "ugly", I got disheartened and gave up. Also I've been using GNOME for a bit with its nice default theme, so I somewhat lost interest in Numix for a while. Sorry.

Let's see if we can get a reasonable compromise into Numix for Xfce users, because that helps people faster. The Xfce people would be happy for contributors to work on virtual resize grips for their compositor mode, but the urgency there among the core team isn't great ([xfce bugzilla 11808](https://bugzilla.xfce.org/show_bug.cgi?id=11808)).

This updated branch applies cleanly onto master again, and obsoletes the branch in the old PR. I'm happy to take suggestions and update this branch with your feedback.

Here's a little preview of what Xfce looks like with this change. This PR currently only touches the bottom border.

patch e04b059 preview

### CODE REVIEW

**Comment by achadwick** [comment]
By the way, what's the reason for the the dark dots in the top-left and top-right corners with this theme? Just something odd I noticed :smile: 

corner_dot

**Comment by khurshid-alam** [comment]
@achadwick 
I have no idea about that `.`

But Can you also provide a screenshot for a gtk-headerbar app like nautilus or gedit ?

**Comment by achadwick** [comment]
@khurshid-alam 
No trouble: <https://user-images.githubusercontent.com/61299/29916683-604c8c9a-8e37-11e7-9f57-e3963cae9fea.png>.

It doesn't seem relevant to this commit, since I only touched the traditional Xfwm theme.

**Comment by achadwick** [comment]
@khurshid-alam 
Hi there - anything more needed for this one?

**Comment by khurshid-alam** [comment]
No. Not really. I am just waiting for @lots0logs to fix the circleci.

**Comment by lots0logs** [comment]
@khurshid-alam Sorry I didn't notice it was failing. I'll look into it asap!

**Comment by khurshid-alam** [comment]
@lots0logs 

It is failing because of version mismatch when it tries to pull sass with gem.

```
ERROR:  Error installing sass:
	sass requires Ruby version >= 2.0.0.
```

We now don't need to install sass with gem. `ruby-sass` is available in debian stretch. So changing the command to `sudo apt-get install ruby-sass` should fix it.

**Comment by achadwick** [comment]
Ah, the mixed blessing of "all checks shall pass". I was wondering whether that was the rule here! :smile:

**Pull request merged**
