### PR TITLE
gtk3.20: row code changed and optimized.

### PR DESCRIPTION
**Pull request by megax**
Base code: https://github.com/GNOME/gtk/blob/master/gtk/theme/Adwaita/_common.scss#L3449

### CODE REVIEW

**Comment by megax** [comment]
@lots0logs Rebase code?

**Comment by lots0logs** [comment]
@megax Yes please. Thanks!

**Comment by megax** [comment]
@lots0logs Rebased :)

**Comment by megax** [comment]
@lots0logs Rebased :)

**Pull request merged**
