### PR TITLE
GTK 3.20 :: Create assets render.

### PR DESCRIPTION
**Pull request by megax**
- Restructure all assets Adwaita and Arc-theme style.
- Fixed all-assets.svg
- Reference PR: https://github.com/numixproject/numix-gtk-theme/pull/549

### CODE REVIEW

**Comment by megax** [comment]
@khurshid-alam, @lots0logs Restructure and regenerate assets and fixed gtk icon scale.

**Comment by khurshid-alam** [comment]
I am not sure if this is required at this moment.

**Comment by megax** [comment]
I believe can improve the display of icons. (HiDPI)

**Comment by khurshid-alam** [comment]
We could easily use svg for HiDPI.....not sure why Gnome keeps using pngs.

**Comment by megax** [comment]
I don't know the answer.

**Comment by megax** [comment]
@lots0logs what do you think?

**Comment by lots0logs** [comment]
@khurshid-alam @megax Just wanted to say that there **_must**_ be a reason why GNOME is still using `pngs` so I think its best that we do the same.

**Pull request merged**
