### PR TITLE
Headerbar :: Separator fix

### LINKED ISSUE #316: gtk3.20: bug
Other:
- Button space:
  image
  image
- Gedit open file list (border):
  image
- csd window not border and not separator titlebar/headerbar: Border fixed: https://github.com/numixproject/numix-gtk-theme/pull/379 Separator fixed: https://github.com/numixproject/numix-gtk-theme/pull/381
  Numix:
  image

Adwaita:
image
- Scrollbar style. Fixed: https://github.com/numixproject/numix-gtk-theme/pull/361
- Tooltip style.

Done:
- Separator bug
- Cinnamon-settings
- Font color bug (font changed light color)
- Selected font color and background
- Nemo icon selected backdrop. (black icon)
- Not overshoot.
- file list
- not spinner
- Combobox not pan-down icon.
- Not window decoration. (_window.scss)
- radio, check button (hover...) bug
- Notebook tab bug
- Notebook tab close button size
- double separator????
- baobab progressbar
- titlebar and headerbar border radius bug
- Popover csd border

### PR DESCRIPTION
**Pull request by megax**
Old:
image

New:
image

Fixes #316

### CODE REVIEW

**Comment by megax** [comment]
@lots0logs Titlebar separator fixed.

**Comment by lots0logs** [comment]
@megax Going forward we'll follow the process outlined in our contributor guidelines (every pull request addresses at least one github issue and all activity during the review of the pull request takes place on the github issue that is being addressed)..but don't worry about it for the PRs you already have open :wink: 

Okay, so back to the change on this PR, let's make the space on each side of the separator equal (probably set it to `$spacing`)

**Comment by megax** [comment]
@lots0logs Okay :)

PR: Not problem spacing. Example (adding button background color):
image

**Comment by lots0logs** [comment]
I see. Since we don't display the minimize/maximize/close buttons as square buttons I think we need to adjust the spacing so that it appears equal (even though it will technically not be equal) Do you know what I mean?

**Comment by megax** [comment]
I can not repair =/

**Pull request merged**
