### PR TITLE
use datadir instead of hardcoding usr/share

### PR DESCRIPTION
**Pull request by bilelmoussaoui**

### CODE REVIEW

**Comment by khurshid-alam** [comment]
@bil-elmoussaoui Please remove gpgsig from your commit and re-open this PR. Thanks.

**Comment by bilelmoussaoui** [comment]
I don't know to do that :P I have created the PR using the github online editor. I will close this and create a correct PR.

**Comment by khurshid-alam** [comment]
OK.

**Comment by Foggalong** [comment]
@bilelmoussaoui Am I missing something or is `$(datadir)` not universally assigned?

**Comment by lots0logs** [comment]
@Foggalong I don't think it is actually. Haven't tried it myself but just from the code itself I don't think this  will work.

**Comment by Foggalong** [comment]
@lots0logs I've checked with Fedora and Ubuntu at least and it's not. Might be on Arch which is I think what Bil uses

**Comment by bilelmoussaoui** [comment]
Must have been something too specific to my old system. Closing this.

**Pull request closed without merging**
