### PR TITLE
Fixes #137

### LINKED ISSUE #137: No Styling on GNOME Clocks Timer
What I am using:
Arch Linux
GNOME 3.12
GNOME Clocks 3.12.0
Numix from Git

The progress circle in the program GNOME Clocks has no styling.

Adwaita:
screenshot from 2014-05-21 00 12 07

Numix:
screenshot from 2014-05-21 00 12 25

Thanks for your continued work on this great theme.

### PR DESCRIPTION
**Pull request by megax**
Fixes #137

### CODE REVIEW

**Comment by khurshid-alam** [comment]
@megax I think it's better not to create `apps/gnome-clocks`. Instead we should put all other gnome apps in `apps/gnome-applications`

**Comment by megax** [comment]
For some reason, there was no `apps/gnome-applications`, it converts.

**Comment by megax** [comment]
Fixed app name.

**Comment by khurshid-alam** [comment]
This won't do anything until you add `$theme_selected_bg_color: $selected_bg_color;`. Anyway I wiil fix this later.

**Pull request merged**
