### PR TITLE
Fixed nautilus active tab border issue

### PR DESCRIPTION
**Pull request by cristatus**
This has fixed nautilus active tab border issue. See the screenshot bellow:
numix

### CODE REVIEW

**Comment by cristatus** [comment]
It also includes a fix for nautilus path bar when using dark color for toolbar (@toobar_bg_color).

**Comment by me4oslav** [comment]
I am not sure we should nuke that 2px border. Maybe try with 1px one?
Oh and we don't have an official dark toolbar spinoff yet (various reasons, once of which being that our icon themes don't have light toolbar icon variation).

**Comment by cristatus** [comment]
Look at the default Adwaita theme. They don't have the bottom border on the active tab. Also, the notebook widget in general doesn't have bottom border on active tab.

For dark toolbar, it just works fine with these changes. I am using Faenza-Darkest icons and it looks perfect. I think it's almost done, you just need to complete light toolbar icons.

I am using dark toolbar with these changes cristatus/Numix@4135959c32a986834a6ddcc8ac93caab10e0cdae

**Comment by me4oslav** [comment]
Right, Numix != Adwaits, so we don't have to follow Adwaita trends, we currently have 1px border below the tabs and I kinda like that. 
http://i.imgur.com/pQSrV60.png
Dark toolbar - before we can have such spinoff (light toolbar will stay the flagmanship one though, probably) of the theme we first need light toolbar icons, so no point of going heals over head and discuss it before we have those icons.
Thanks you for your contribution, but it seems it will bring a change we simply don't want or need, so we're not merging it.
Don't be discouraged to contribute to Numix for the future, though.
Cheers! :)

**Comment by cristatus** [comment]
For dark toolbar, no, it doesn't bring any change. The toolbar remains light. It's only fixing a rendering issue if you change @toolbar_bg_color manually.

BTW, do you know how the nautilus tab is rendered in gnome 3.6? It seems there is some change in 3.8 that caused that line. Almost all thirdparty gtk3 themes in 3.8 have this line but in 3.6 they don't. Only the default `Adwaita` theme retained the same rendering, so obviously it's by mistake.

Anyway, I am happy with my fork and will keep it in sync. I am just an end user not a designer so can't argue much but this is what I feel better.

Thanks again!

**Comment by satya164** [comment]
@cristatus First of all, many many thanks for the pull request. Sorry, I cannot merge it due to the following reasons.
- We need to fix the dark toolbar issue for all apps, not just nautilus.
- It's a bit hacky.

Hope it doesn't discourage you and prevent you from doing new pull requests.

**Comment by satya164** [comment]
I have fixed the dark toolbar issue in master for all apps. Do check.

**Comment by cristatus** [comment]
Thanks. BTW, I have promoted the darker version on gnome-look to aspire you to adopt it quickly. I really appreciate your work. I also suggest you to review my nautilus tabs related changes. IMO, it looks better. Yes, it's hackish but I don't found any better way to do this (as I said, I am not a designer :)).

Thanks again!

**Comment by satya164** [comment]
@cristatus You're welcome :)

I have to say, I haven't decided on whether we should have the border below the tabs. But if I want to remove it, I have to find a better way, and it'll be much better to do this for all apps such as gedit etc., not just for nautilus.

**Pull request closed without merging**
