### PR TITLE
whisker menu & mintmenu support

### PR DESCRIPTION
**Pull request by geplus**
whisker menu & mintmenu support

### CODE REVIEW

**Comment by lots0logs** [comment]
@geplus Could you provide us with some before & after screenshots? Even though I generally dislike the idea of merging based on screenshots alone I think it might be okay in this specific case.

**Comment by khurshid-alam** [comment]
@geplus You need to combine #293 and #294 and this into a single commit. Three separate pull requests for a single issue is not recommended.

**Comment by megax** [comment]
@khurshid-alam now this is how? https://github.com/numixproject/numix-gtk-theme/issues/240 https://github.com/numixproject/numix-gtk-theme/commit/61c81012cff3f854780ddbd13aa5cb192b010b38

**Comment by megax** [comment]
@khurshid-alam @lots0logs and @geplus Whisker menu added by @ochosi : https://github.com/numixproject/numix-gtk-theme/commit/61c81012cff3f854780ddbd13aa5cb192b010b38

Please close 3 PR and create new PR only mintmenu.

**Pull request closed without merging**
