### PR TITLE
GTK 3.20 :: Color chooser rewirte

### PR DESCRIPTION
**Pull request by megax**
**Before:**
anim

**After:**
anim

Base code: Adwaita

### CODE REVIEW

**Comment by lots0logs** [comment]
@megax I like the idea of the colors' edges being beveled on-hover but I don't like the dark (almost black) border that I see in your gif. I havent tested it locally yet though. I'll try and get to it asap.

**Comment by khurshid-alam** [comment]
This is actually breaking all apps using gtk <= 3.16. Not sure why(?).

**Comment by lots0logs** [comment]
@khurshid-alam Are you sure? I don't see how that's possible :confused:

**Comment by khurshid-alam** [comment]
Ahh...sorry.....It was getting overridden by `~/.config/gtk-3.0/gtk.css` which I forgot to remove. :(

**Comment by megax** [comment]
@lots0logs Tests were succesfull? 
If you want to modify the borders, please do it, beacue I don't know what would be ideal for you!

**Comment by megax** [comment]
@lots0logs Any news? :)

**Pull request merged**
