### PR TITLE
GTK 3.20 :: Calendar rewirte

### PR DESCRIPTION
**Pull request by megax**
**Before:**
image

**After:**
image

### CODE REVIEW

**Comment by khurshid-alam** [comment]
@megax Padding is messed up. Rather use `1px 3px` padding throughout the code.

Result:
calendar-padding

**Comment by megax** [comment]
@khurshid-alam Fixed :)
image

**Comment by khurshid-alam** [comment]
@megax This causes problems with Unity panel calendar. (Ubuntu 16.10, Gtk-3.20) ?

unity-calendar-bug

**Comment by megax** [comment]
Unity panel be amended. Created specific calendar code.

**Comment by megax** [comment]
@khurshid-alam I think it will be a problem: https://github.com/numixproject/numix-gtk-theme/blob/d24e294920d851226b4109ddb0fa45a9253d86e9/gtk-3.20/scss/widgets/_menu.scss#L116

**Pull request merged**
