### PR TITLE
GTK 3.20 :: Fixes #370

### LINKED ISSUE #370: Highlight of focused button
It is not easily visible which button is focused.

In this case it is the delete/Löschen button which has a slight shadow.

### PR DESCRIPTION
**Pull request by megax**
image

### CODE REVIEW

**Comment by megax** [comment]
@khurshid-alam, @lots0logs, @SammysHP Opinion? :)

**Comment by khurshid-alam** [comment]
@megax 

It works, but the idea is much better suited for more flatter button....for example how our gtk2 button are. But gtk3 buttons are not that flat...so I am not sure.

See how gtk2 button are absolutely flat...
gtk2-button

**Comment by megax** [comment]
Of course, I understand. Only examples idea :)

**Edit:** There are other fundamental problems too. You should totally watch button code...

**Comment by SammysHP** [comment]
I really like the gtk2 version with the dotted inner border.

**Comment by megax** [comment]
I'll make changes.

**Comment by lots0logs** [comment]
@megax RE: dotted inner border, :-1:  (sorry :grimacing: )

**Comment by megax** [comment]
@lots0logs I do not want dotted... :P

**Comment by megax** [comment]
@lots0logs I do not want dotted... :P

**Edit:** What are you the idea? :)

**Comment by lots0logs** [comment]
@megax Hmm.. maybe simply change the font-style in a noticeable way for focus state (like the weight or color). Another option would be to make color of the box shadow based off of $selected_bg_color. Thoughts?

**Comment by megax** [comment]
> Another option would be to make color of the box shadow based off of $selected_bg_color. 

Like :)

But separated should choose focus and hover code.

**Comment by khurshid-alam** [comment]
> Another option would be to make color of the box shadow based off of $selected_bg_color. 

That is exactly my line of thinking...I actually tried that before.....but it will be even better if buttons are little more flatter. Otherwise the color makes it too prominent for some apps which place button in the headerbar (like geary).

So I propose two things:
1. Make buttons more flatter.
2. Then we have two options:
   a) box shadow of focus button> $selected_bg_color
   b) change the color of focus button with relative brightness (as suggested in this PR)

> But separated should choose focus and hover code.

Only focus state should change. Hover is fine. No?

**Comment by megax** [comment]
@khurshid-alam https://github.com/numixproject/numix-gtk-theme/blob/master/src/gtk-3.20/scss/widgets/_button.scss#L293 common attributes

**Comment by lots0logs** [comment]
I have a feeling that using exactly $slected_bg_color for the shadow won't look great. Might need to mix it or lighten it a bit.

**Comment by megax** [comment]
Now I do not know exactly how it should be (Desing optimisation... not my forte =/). But I think of something. But if you intervene to solve other, i do not mind. :)

**Comment by khurshid-alam** [comment]
Flatter Button (draft)

``` css
--- a/src/gtk-3.20/scss/widgets/_button.scss
+++ b/src/gtk-3.20/scss/widgets/_button.scss
@@ -280,7 +280,7 @@
     @include border(rgba(0, 0, 0, .12 + $border_strength));

     color: $fg;
-    box-shadow: 0 1px 2px -1px alpha($dark_shadow, .12 + $shadow_strength);
+    //box-shadow: 0 1px 2px -1px alpha($dark_shadow, .12 + $shadow_strength); /makes flatter

     &.flat {
         border-color: alpha($button_bg, 0);
@@ -294,7 +294,7 @@
             @include linear-gradient(shade($button_bg, 1.2));
             @include border(rgba(0, 0, 0, .2 + $border_strength));

-            box-shadow: 0 1px 2px -1px alpha($dark_shadow, .32 + $shadow_strength);
+            //box-shadow: 0 1px 2px -1px alpha($dark_shadow, .32 + $shadow_strength); 
+            // change shadow color ?
         }

         &:checked, &:active {
```

Linked button and vertical linked button need to modified as well.

**Comment by megax** [comment]
Perhaps sharper border? (just idea) `border(rgba(0, 0, 0, .2 + $border_strength)) -> border(rgba(0, 0, 0, .4 + $border_strength))`

```
    &, &.flat {
        &:focus, &:hover {
            @include linear-gradient(shade($button_bg, 1.2));
            @include border(rgba(0, 0, 0, .4 + $border_strength)); /* Megax fix. */

            box-shadow: 0 1px 2px -1px alpha($dark_shadow, .32 + $shadow_strength);
        }
```

**Comment by megax** [comment]
Perhaps sharper border? (just idea)

```
megax@Jakosa:~/.themes/Numix-origin$ (master *=)
⚡ git diff
diff --git a/src/gtk-3.20/scss/widgets/_button.scss b/src/gtk-3.20/scss/widgets/_button.scss
index 429b3c2..ac1af41 100644
--- a/src/gtk-3.20/scss/widgets/_button.scss
+++ b/src/gtk-3.20/scss/widgets/_button.scss
@@ -292,7 +292,7 @@
     &, &.flat {
         &:focus, &:hover {
             @include linear-gradient(shade($button_bg, 1.2));
-            @include border(rgba(0, 0, 0, .2 + $border_strength));
+            @include border(rgba(0, 0, 0, .25 + $border_strength));

             box-shadow: 0 1px 2px -1px alpha($dark_shadow, .32 + $shadow_strength);
         }
megax@Jakosa:~/.themes/Numix-origin$ (master *=)
⚡ 
```

anim

**Comment by khurshid-alam** [comment]
Right. Border can be made sharper. 

Also I tried with `box-shadow: 0 1px 2px -1px rgba(240,84,76, 0.5);`......but that didn't feel right....it also started producing shadow under breadcrumbs.

So stronger border probably only way to go....or we could introduce default button state like in 3.18.

**Comment by khurshid-alam** [comment]
I pushed few changes. But we can not fix this properly without separating button code with header-bar button.

**Pull request closed without merging**
