### PR TITLE
Fixed #304

### LINKED ISSUE #304: GNOME documents, books, Videos (totem), Photos etc selection checkbox does not appear
The check symbol on selection mode with all those similar "collection" applications doesn't appear at all.

In the following screenshot I selected all the Landau and Lifshiftz physics books on Documents (the program's top bar tells of 6 selected items), but I cannot see a symbol on the checkbox while using Numix GTK3 theme

screenshot from 2016-04-02 16-45-28

### PR DESCRIPTION
**Pull request by megax**
GTK 3.20 (sample icon `svg`, but it is also good with `png`):
anim

### CODE REVIEW

**Comment by megax** [comment]
@khurshid-alam Please test gtk 3.18

**Comment by khurshid-alam** [comment]
We should use svgs though. The new svgs can be found here: https://github.com/numixproject/numix-gtk-theme/files/416643/numix-assets.zip

**Comment by megax** [comment]
I create PR? :)

**Comment by khurshid-alam** [comment]
Yes. If you can. But make sure to remove executable permission from those files if any.

**Pull request merged**
