### PR TITLE
GTK 3.20 :: Fixed unity-panel calendar color

### PR DESCRIPTION
**Pull request by megax**
https://github.com/numixproject/numix-gtk-theme/pull/412#issuecomment-242899918

Sample:
image

### CODE REVIEW

**Comment by megax** [comment]
@khurshid-alam Fixed.

**Comment by khurshid-alam** [comment]
@megax 

Gtk-3.22: Calendar text is unreadable again inside searchbar (nautilus-3.20), Can you provide a fix?

calendar

**Comment by megax** [comment]
I look :)

**Comment by khurshid-alam** [comment]
@megax  Fixed in 0220883625c

**Comment by megax** [comment]
@khurshid-alam Ohh. Okay :)

**Pull request merged**
