### PR TITLE
Readme update

### PR DESCRIPTION
**Pull request by megax**

### CODE REVIEW

**Comment by megax** [comment]
@lots0logs @khurshid-alam Updated gtk 3.18 :)

**Comment by lots0logs** [comment]
Actually those badges are meant to display the minimum and maximum GTK versions supported by the theme. I'm not sure which version of GNOME is in 16.04 though. If its 3.18 then I think its okay to change it in the README.

**Comment by megax** [comment]
Yeah I know :)
@khurshid-alam updated minimal gtk version: https://github.com/numixproject/numix-gtk-theme/commit/c5652230d7a86e45160ec5703402f3d38e21b358

**Comment by lots0logs** [comment]
homer-simpson-doh

**Comment by khurshid-alam** [comment]
Thanks. Somehow I missed that.

**Pull request merged**
