### PR TITLE
GTK 3.20 :: Implement scale color code

### PR DESCRIPTION
**Pull request by megax**
**Before:**
anim

**After:**
anim

### CODE REVIEW

**Comment by khurshid-alam** [comment]
@megax This looks awkward. Can you show me a screenshot with inline -spinbutton in it? (just right click to make it appear)

**Comment by megax** [comment]
image

I not fixed popup background bug.

**Comment by megax** [comment]
@khurshid-alam Which is awkward? The modified one or the other one!?

**Comment by khurshid-alam** [comment]
@megax 

> Which is awkward? The modified one or the other one!?

The modified one. You are drawing color scale within box leaving transparent area behind. See old design here:
old scale

> I not fixed popup background bug.

I can see that. And that spinbutton used to be dark (as shown in the above image).......it seems all other themes also use dark spinbutton on color scale (irrespective of variant).....although I am not sure if we, now, can achieve something like that.

**Comment by megax** [comment]
Osd repair-> dark button.
Later modified color scale style old style. Okay? :)

Sample:
image
I later fix (PR).

**Comment by megax** [comment]
Adwaita theme scale color:
image

**Comment by lots0logs** [comment]
I actually prefer how it is now though I think it could be just a bit wider (but not as wide as it was in old versions)

**Comment by megax** [comment]
@khurshid-alam, @lots0logs Corrected old style. I what to improve on it?
anim

**Comment by SammysHP** [comment]
That looks good, maybe a little bit smaller (so that the handle slightly overlaps).

**Comment by lots0logs** [comment]
@megax These changes need to be done in a way that affects only the color scales. You can use the `.color` style class to do it (so the top-level selector for these changes would be `scale.color`).

**Comment by megax** [comment]
@lots0logs What would you like, what class is it look like? Take it out from the scale class?

**Comment by lots0logs** [comment]
@megax Actually, nevermind, I was looking at the wrong thing. Sorry :sweat_smile:

**Pull request merged**
