### PR TITLE
GTK 3.20 :: Fixed #463

### LINKED ISSUE #463: GTK 3.20 :: Volume bug
Bug:
- Background color and volume button
- Slider and arrow button padding

Test app: gtk3-widget-factory

image

### PR DESCRIPTION
**Pull request by megax**
Fixed global scale design (padding):
image

Fixed #463 (fixed osd code):
image

### CODE REVIEW

**Comment by megax** [comment]
@lots0logs @khurshid-alam Fixed issue.

**Comment by megax** [comment]
You should be modified?

**Comment by megax** [comment]
@khurshid-alam https://github.com/numixproject/numix-gtk-theme/pull/542 and https://github.com/numixproject/numix-gtk-theme/pull/535 merged, i rebase PR and fix `.osd`.

**Comment by khurshid-alam** [comment]
@megax 

Please move back osd toolbar code to `_osd.scss`. Osd toolbar, entry, button, spinbutton etc must stay **inside** _osd.scss.

**Comment by megax** [comment]
@khurshid-alam Done.

**Comment by khurshid-alam** [comment]
@megax Please rebase again.

**Comment by megax** [comment]
@khurshid-alam Done.

**Pull request merged**
