### PR TITLE
gtk3.20: Scrollbar slider margin 1px fix. (Old numix style)

### PR DESCRIPTION
**Pull request by megax**

### CODE REVIEW

**Comment by megax** [comment]
@lots0logs Scrollbar desing fix. (Old style)

**Comment by megax** [comment]
@lots0logs I have tried to change the style of the scrollbar a bit. I thought it would be good if it would look like the old one. I have checked at the gnome-terminal too. That needs a fix too. If you have any idea about the scrollbar or its design, please contact me :)

**Comment by lots0logs** [comment]
Could you post a screenshot of the old one? I dont have quick/easy access to view it at the moment since I'm running 3.20.

**Comment by megax** [comment]
only... gnome-terminal: 
image

**Comment by megax** [comment]
@lots0logs Maybe @satya164 , Could @khurshid-alam  send some pictures about the scrollbar? I suspect they might be running the older gtk version. (I have to use gtk3.20 becouse I have archlinux on my PC)

**Comment by khurshid-alam** [comment]
@megax 

Screenshot (with GTK-3.18): 

nautilus-scroll

Ignore the color variation on the gif as it is highly compressed.
gif

**Comment by megax** [comment]
Thanks :)

**Pull request merged**
