### PR TITLE
GTK 3.22 :: Fixes #634

### LINKED ISSUE #634: System Settings
Hi, can improve (change) the System Settings (white) background? 
Thanks.
system settings_033

And, where can I post the issue regarding selected icons... they have pixelated edges. This annoys me since long time ago. Look above on the "Online Accounts" icon for example

### PR DESCRIPTION
**Pull request by megax**
Thanks code format adapta theme: https://github.com/adapta-project/adapta-gtk-theme/blob/cefe3f0d2510b818219b89c60e9b156665e493dd/gtk/sass/3.22/_3rd-party.scss#L1186

**Example:**
image

### CODE REVIEW

**Comment by leoheck** [comment]
@megax how the mouse hover looks now? Can you make a new screenshot selecting an icon?

**Comment by khurshid-alam** [comment]
Only for 3.22?

**Comment by megax** [comment]
@khurshid-alam 3.20 and 3.22, not support icon effect. Only background bug fix.

**Comment by khurshid-alam** [comment]
It doesn't work for 3.20.

**Comment by megax** [comment]
I tested Ubuntu 16.10. I do not understand =/

**Comment by leoheck** [comment]
How can I install this pull request to give it a try?

Edit: Ok, I figured out. Using this:
```
git fetch origin pull/2/head
git checkout -b <local_branch_name> FETCH_HEAD
```

**Comment by leoheck** [comment]
@khurshid-alam, PR works for me using Ubuntu 16.10. Later, at work, I can test in Ubuntu 16.04.
Mouse is over language support.

image

**Pull request merged**
