### PR TITLE
GTK 3.20 :: Fixes #585

### LINKED ISSUE #585: GTK 3.22 :: System Monitor :: white points on the left and right sides
system monitor

### PR DESCRIPTION
**Pull request by megax**
image

### CODE REVIEW

**Comment by megax** [comment]
@khurshid-alam Please test ubuntu. (Ubuntu nocsd config mode... 1-2px bug...)

**Edit:** Related comment: https://github.com/numixproject/numix-gtk-theme/pull/521#issuecomment-244219383

> For 3.20 if I apply same fix after merging this, It fixes the issue but there remains a white dot between Unity titlebar and window.

**Comment by megax** [comment]
Tested, fixed bug.

Sample (my color theme):
image

Minimal... minimal... Ubuntu special... bug :) : 1px dark pixel border-radius csd window. But just Ubuntu. Something ruined gtk engine... the uncorrectable.

**Comment by khurshid-alam** [comment]
I will merge this after I tweak Unity's window border color.

**Comment by megax** [comment]
I know, it was just a remainig error/bug, what we couldn't repair in the PR.

**Pull request merged**
