### PR TITLE
GTK 3.20 :: Optimized Nemo and Nautilus design and update searchbar code

### PR DESCRIPTION
**Pull request by megax**
Optimized:
- Removed Nautilus duplicated paned border.
- Nautilus searchbar backgorund color.
- Nautilus backdrop mode not text color change.
- Nemo statusbar button size and padding. (satusbar too high)
- Nemo searchbar background color.

Updated:
- Searchbar and location-bar code.

**Before:**
image

**After:**
image

### CODE REVIEW

**Comment by megax** [comment]
Fixed issue: #272 
image

**Comment by lots0logs** [comment]
@megax The search bar background should use the `theme_selected_bg_color`. That was a recent and intentional change from what it was in the old version of the theme :wink: 

**Edit:** Also the dropdown on nautilus search was also intentional.

**Comment by megax** [comment]
@lots0logs Before I looked everything about it but I couldn't find in this form, and if I remember well it have never been with `theme_selected_bg_color` color. On the other hand it is really wrong to do with `theme_selected_bg_color` beacuse it indicates warning.

## **Old code:**

**search-bar:** https://github.com/numixproject/numix-gtk-theme/blob/v2.5.1/gtk-3.0/gtk-widgets.css#L3297
**Nautilus:** https://github.com/numixproject/numix-gtk-theme/blob/v2.5.1/gtk-3.0/apps/gnome-applications.css#L81)

**gtk 3.18 (Nautilus):**
image

Not used `theme_selected_bg_color`.

**Comment by lots0logs** [comment]
@megax I know it wasn't using selected background color in the old version. I recently changed it. I should have been more clear about that. Sorry! The theme's color is red, yes that is typically used to indicate a warning but in this case I think its pretty obvious why the background is red for that area (same as its obvious why the background is blue for that same area in Numix Frost :wink: )

**Comment by khurshid-alam** [comment]
For recursive search (in Yakkety), search-bar will turn red ($error_color) when search items are not found. So we need to use different color; either for  $error_color or for search-bar background color. But this can be carried as a patch for Ubuntu/Debian only.

**Comment by megax** [comment]
@khurshid-alam @lots0logs What can I change that? :)

**Comment by khurshid-alam** [comment]
@lots0logs Search-bar background color is same as `GTK_MESSAGE_ERROR` in infobar. So we need to change one of these. Your thoughts?
infobar

**Comment by lots0logs** [comment]
@khurshid-alam I think we need to change the error background only because we should not use the theme's primary color for any of the GTK message types as they are supposed to be easily distinguishable from the theme itself.

**Comment by khurshid-alam** [comment]
@megax I want to merge code change from nautilus paned, but it seems you completely remove it instead of setting it transparent. I am experiencing issues like missing icons, shell-crashes when I lock screen and then unlock or during logout-login or during vnc session from other machines. Are you experiencing any similar issues on Arc?

**Comment by megax** [comment]
@khurshid-alam Not reproduced (virtualbox arch linux) lock and unlock crash. (gnome 3.20) And not bug cinnamon. (nemo full replace nautilus)
anim

**Pull request merged**
