### PR TITLE
symlink for dash/style-sheet icons

### PR DESCRIPTION
**Pull request by andia89**
According to a comment in this bug:

https://github.com/shimmerproject/Numix/issues/122

I created a pull request for this bug. I hope everything worked since this is the first pull request I made :)

### CODE REVIEW

**Comment by mzur** [comment]
According to the [theming guide](https://wiki.ubuntu.com/Unity/Theming) the links should be in an `icons/` subdirectory. For example: `$THEME_PATH/unity/icons/close_dash.{svg, png}`. Does it work for you? Maybe the subdirectory is optional.

**Comment by andia89** [comment]
it definitely works, and since all the other icons aren't in an subfolder either, I think we can ignore that

**Comment by Tammuz** [comment]
For me it does not work.

edit: Works fine now! But it hasn't still been included as dafault?

**Comment by andia89** [comment]
I changed it accordingly. Surprisingly both ways work for me...

**Pull request merged**
